# .github/workflows/deploy.yml

name: Deploy xphc App to S3

on:
  push:
    branches:
      - master  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the version of Node.js required for your project

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET_NAME: xphc #${{ secrets.S3_BUCKET_NAME }}
      run: |
        aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
        aws s3 website s3://$S3_BUCKET_NAME/ --index-document index.html --error-document index.html

  