name: Deploy XPHC
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x]
    steps:
     - uses: actions/checkout@main
     - run: npm install
     - run: npm run build
#      - run npm est
     - uses: jakejarvis/s3-sync-action@master
       with:
        args: --acl public-read --follow-symlinks --delete
       env:
            AWS_S3_BUCKET: 'xphc'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1' 
            SOURCE_DIR: 'build'

      